spring:
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice
    username: microservice
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body
    # Raw password: microservice
    password: "{cipher}c5c54009a56a0f215a208067a2b13189091c13480306c81ab68edfb22a6251ca"
  jooq:
    sql-dialect: POSTGRES_9_5

security:
  restApi:
    authenticationInformation: http://localhost:5555/security/oauth/check_token?token={token}
    clientId: Spring5Microservices
    # Raw password: Spring5Microservices
    clientPassword: "{cipher}95db5fce892a2f48d9b93e2bfabf67e5bc84d50a18d1265777cfc547a1185f1cab5c4bbc96b5f6fb4fda66fec6f83f87"



# TODO: Remove from here
authentication:
  restApi:
    authenticationInformation: http://localhost:5555/authentication/authinfo/{token}